import type { SceneSpec } from "./types";

export const CH0_SCENES: SceneSpec[] = [
  {
    id: "0-1",
    chapter: 0,
    kind: "owlNarration",
    owl: "serious",
    timeOfDay: "sunset",
    bgImage: "/vision_express/common/departing-train.webp",
    hideOwl: true,
    hideSpeakerLabel: true,
    bgm: "kauasilbershlachparodes-train-493986.mp3",
    narration: "비전 익스프레스 열차가 출발합니다.",
    next: "0-2",
  },
  {
    id: "0-2",
    chapter: 0,
    kind: "owlNarration",
    owl: "welcoming",
    timeOfDay: "sunset",
    hideSpeakerLabel: true,
    lines: [
      "어서 오십시오.",
      "마침내 {name}님을 위한 여정이 시작되었군요.",
    ],
    next: "0-2-1",
  },
  {
    id: "0-2-1",
    chapter: 0,
    kind: "binaryChoice",
    owl: "explaining",
    timeOfDay: "sunset",
    hideSpeakerLabel: true,
    lines: ["자리는 편안하신가요?"],
    choices: [
      { label: "네, 편안해요", next: "0-2-1a" },
      { label: "조금 어색해요", next: "0-2-2" },
    ],
  },
  {
    id: "0-2-1a",
    chapter: 0,
    kind: "owlNarration",
    owl: "approving",
    timeOfDay: "sunset",
    hideSpeakerLabel: true,
    lines: ["편안하시다니 다행이에요."],
    next: "0-3",
  },
  {
    id: "0-2-2",
    chapter: 0,
    kind: "question",
    owl: "listening",
    timeOfDay: "sunset",
    hideSpeakerLabel: true,
    lines: ["어떤 부분이 어색하신가요?"],
    placeholder: "편하게 적어주세요",
    saveTo: "awkwardnessFeedback",
    buttonLabel: "건네기",
    next: "0-2-3",
  },
  {
    id: "0-2-3",
    chapter: 0,
    kind: "owlReflect",
    owl: "approving",
    timeOfDay: "sunset",
    hideSpeakerLabel: true,
    reflectTask: "comfortReassure",
    reflectInputField: "awkwardnessFeedback",
    buttonLabel: "다음",
    next: "0-3",
  },
  {
    id: "0-3",
    chapter: 0,
    kind: "owlNarration",
    owl: "scrutinizing",
    timeOfDay: "sunset",
    lines: [
      "저는 오늘 {name}님의 이야기를 기록할 매거진 STORY의 편집장 엘아울(L-OWL)입니다.",
    ],
    next: "0-4",
  },
  {
    id: "0-4",
    chapter: 0,
    kind: "owlNarration",
    owl: "contemplating",
    timeOfDay: "sunset",
    bgImage: "/vision_express/common/Chapter_01.webp",
    hideOwl: true,
    lines: [
      "창밖을 보시죠.",
      "우리가 떠나온 곳 위로 붉은 해가 저물고 있습니다.",
      "일몰은 — 하루를 돌아보고, 어깨에 얹어둔 것들을 잠시 내려놓기에 좋은 시간이지요.",
    ],
    next: "0-5",
  },
  {
    id: "0-5",
    chapter: 0,
    kind: "ritual",
    owl: "offering",
    timeOfDay: "sunset",
    lines: [
      "{job} 관련 일을 하고 계셨군요...",
      "{name}님 이름 앞에 붙은 수식어와 직함들 —",
      "아마도 그건 치열하게 살아오신 '빛나는 흔적'일 거예요.",
      "하지만 이 프라이빗 객실에서만큼은, 그 무거운 외투를 잠시 의자에 벗어두셔도 괜찮아요.",
    ],
    buttonLabel: "네, 그럴게요",
    next: "0-5-narr",
  },
  {
    // 외투를 벗는 비트 — 사용자가 "네, 그럴게요" 후 의자에 외투를
    // 걸어두는 짧은 ambience 장면.
    id: "0-5-narr",
    chapter: 0,
    kind: "ambience",
    owl: "offering",
    hideOwl: true,
    cinematic: true,
    timeOfDay: "sunset",
    bgImage: "/vision_express/common/Chapter_01.webp",
    narration: "외투를 벗어놓는다.",
    next: "0-5-1",
  },
  {
    id: "0-5-1",
    chapter: 0,
    kind: "ritual",
    owl: "listening",
    timeOfDay: "sunset",
    lines: [
      "좋아요.",
      "한 가지 먼저 말씀드릴게요.",
      "여기서 {name}님이 적으시는 모든 이야기는 오직 {name}님만 볼 수 있어요.",
      "외부에 공개되지 않고, 저와 {name}님 사이에만 있는 이야기예요.",
      "이 객실은 {name}님만의 공간이에요.",
    ],
    buttonLabel: "네, 이해했어요",
    next: "0-6",
  },
  {
    id: "0-6",
    chapter: 0,
    kind: "ritual",
    owl: "listening",
    timeOfDay: "sunset",
    lines: [
      "저는 평생 사람들의 이야기를 들어왔어요.",
      "그리고 그 이야기로, 그 사람만을 위한 단 한 호의 매거진을 만들어왔죠.",
      "이 호는 어디에도 팔리지 않아요.",
      "솔직하게 저와 이야기할 준비, 되셨나요?",
    ],
    buttonLabel: "네, 준비됐어요",
    next: "1-card",
  },
];
