import { INTERVIEW_OWL_POOL, type SceneSpec } from "./types";
import { EMPATH_OPENERS, RECEIVE_OPENERS } from "./openers";

export const CH1_SCENES: SceneSpec[] = [
  {
    id: "1-card",
    chapter: 1,
    kind: "chapterCard",
    timeOfDay: "sunset",
    bgm: "benkirb-shine-10-268906.mp3",
    next: "1-0",
  },
  {
    id: "1-0",
    chapter: 1,
    kind: "owlNarration",
    owl: "offering",
    timeOfDay: "sunset",
    lines: [
      "좋아요, {name}님.",
      "첫 번째 챕터부터 시작할게요.",
      "저는 사람들에게 이런 말을 자주 해요.",
      "한 사람의 이야기는 만드는 게 아니라 발견하는 것이라고.",
      "그리고 그 발견은 거의 항상 같은 곳에서 시작돼요.",
      "'그 사람이 시간 가는 줄 모르고 빠져들었던 순간' — 거기에 그 사람만의 감각이 숨어있거든요.",
      "거창한 이야기가 아니어도 돼요.",
      "오히려 작고 구체적일수록 좋습니다.",
    ],
    next: "1-1-pre",
  },
  {
    id: "1-1-pre",
    chapter: 1,
    kind: "owlNarration",
    owl: "serious",
    timeOfDay: "sunset",
    lines: [
      "자, 그럼 시작해볼까요.",
      "눈을 한 번 감아보세요.",
      "일하면서 시간 가는 줄 모르고 빠져들었던 순간을 떠올려보세요.",
    ],
    next: "1-1-guide",
  },
  {
    id: "1-1-guide",
    chapter: 1,
    kind: "owlNarration",
    owl: "serious",
    timeOfDay: "sunset",
    lines: [
      "꼭 지금 하는 일이 아니어도 좋아요.",
      "작은 업무여도, 예전 프로젝트의 한 장면이어도 좋습니다.",
    ],
    next: "1-1",
  },
  {
    id: "1-1",
    chapter: 1,
    kind: "question",
    owl: "serious",
    timeOfDay: "sunset",
    lines: [
      "가장 먼저 마음에 떠오르는 한 장면 — 그 안에서 {name}님은 무엇을 하고 계셨나요?",
    ],
    inputHint: "언제, 어디서, 무엇을 했는지 떠오르는 대로 적어주세요. 정리하지 않아도 좋아요.",
    placeholder: "예: 작년에 처음으로 혼자 기획서를 만들었을 때, 생각보다 잘 만들어져서 뿌듯했어요.",
    editorNote: "저는 아무것도 몰라요. 자세히 말씀해주실수록, {name}님의 발견을 도와드릴 수 있습니다.",
    saveTo: "flowExperience1",
    buttonLabel: "건네기",
    next: "1-2",
  },
  {
    id: "1-2",
    chapter: 1,
    kind: "followup",
    owl: "thinking",
    owlPool: INTERVIEW_OWL_POOL,
    timeOfDay: "sunset",
    judge: "judgeBranch",
    parentSaveTo: "flowExperience1",
    maxFollowups: 2,
    branches: {
      A: {
        narration: "편집장이 잠시 멈춘다. 이야기는 있다. 그런데 아직 더 깊은 곳이 남아 있다.",
        openerPool: EMPATH_OPENERS,
        lines: [
          "그때 {name}님 안에서는 어떤 마음이 움직이고 있었나요?",
          "설렘이었을까요, 몰입이었을까요, 아니면 또 다른 무엇이었을까요.",
        ],
        inputHint: "그때 {name}님 안에서 움직이던 감각을 있는 그대로 적어주세요.",
      },
      B: {
        narration: "편집장이 페이지 위로 몸을 살짝 기울인다. 좀 더 가까이 가봐야겠다.",
        openerPool: RECEIVE_OPENERS,
        lines: [
          "그 중에서도 가장 또렷하게 떠오르는 한 장면이 있다면 — 어떤 모습인가요?",
          "어디에서, 누구와, 무엇을 하고 계셨는지 그려주세요.",
        ],
        inputHint: "힌트: 어디에 있었나요? 누구와 함께였나요? 무엇을 하고 있었나요?",
      },
      D: {
        next: "1-3",
        exhaustedLines: ["지금 이 이야기, 그대로 가져가볼게요."],
      },
    },
    buttonLabel: "건네기",
  },
  {
    id: "1-3",
    chapter: 1,
    kind: "question",
    owl: "focusedWriting",
    owlPool: INTERVIEW_OWL_POOL,
    timeOfDay: "sunset",
    narration: "편집장이 펜을 들어 첫 번째 이야기를 매거진 한 켠에 적는다. 그리고 다시 {name}님을 바라본다.",
    lines: [
      "한 가지만 더 여쭤볼게요.",
      "그런데 그런 순간이 한 번뿐은 아닐 것 같아요.",
      "결은 조금 다르더라도, 비슷하게 빠져들었던 또 다른 순간이 있다면 — 어떤 장면이 떠오르세요?",
    ],
    inputHint: "첫 번째와 전혀 다른 상황이어도 좋아요. 떠오르는 대로 적어주세요.",
    editorNote: "꼭 회사에서 있었던 일이 아니라도 괜찮아요.",
    saveTo: "flowExperience2",
    buttonLabel: "건네기",
    next: "1-4",
  },
  {
    id: "1-4",
    chapter: 1,
    kind: "followup",
    owl: "thinking",
    owlPool: INTERVIEW_OWL_POOL,
    timeOfDay: "sunset",
    judge: "judgeBranch",
    parentSaveTo: "flowExperience2",
    maxFollowups: 2,
    branches: {
      A: {
        narration: "이번에도 편집장은 조금 더 들어가기로 한다.",
        openerPool: EMPATH_OPENERS,
        lines: [
          "그 안에서 {name}님을 가장 깊이 끌어당긴 건 무엇이었어요?",
          "사람이었을까요, 일 자체였을까요, 아니면 만들어지던 결과였을까요.",
        ],
        inputHint: "그때 {name}님을 끌어당기던 것을 떠오르는 대로 적어주세요.",
      },
      B: {
        narration: "편집장이 부드럽게 방향을 다시 잡는다.",
        lines: [
          "잠깐만요.",
          "그 장면을 한 토막의 영상처럼 그려주실래요?",
          "{name}님 시야에 있던 것, 들리던 소리, 손에 닿던 것 — 작은 디테일 한두 개면 충분해요.",
        ],
        inputHint: "아주 작은 것 하나면 충분해요.",
      },
      D: {
        next: "1-4z",
        exhaustedLines: ["지금 이 이야기, 그대로 가져가볼게요."],
      },
    },
    buttonLabel: "건네기",
  },
  {
    id: "1-4z",
    chapter: 1,
    kind: "owlNarration",
    owl: "focusedWriting",
    owlPool: INTERVIEW_OWL_POOL,
    timeOfDay: "sunset",
    narration: "편집장이 두 이야기를 나란히 놓고 잠시 들여다본다. 그리고 천천히 입을 연다.",
    lines: ["두 이야기를 가만히 들어보니, 이렇게 읽혀요."],
    next: "1-5",
  },
  {
    id: "1-5",
    chapter: 1,
    kind: "ch1Keyword",
    owl: "scrutinizing",
    timeOfDay: "sunset",
    next: "1-5b",
  },
  {
    id: "1-5b",
    chapter: 1,
    kind: "owlNarration",
    owl: "focusedWriting",
    owlPool: INTERVIEW_OWL_POOL,
    timeOfDay: "sunset",
    lines: ["이 결이 맞을지, 다음 질문으로 넘어가볼게요."],
    next: "1-5q",
  },
  {
    id: "1-5q",
    chapter: 1,
    kind: "question",
    owl: "thinking",
    owlPool: INTERVIEW_OWL_POOL,
    timeOfDay: "sunset",
    lines: [
      "이제 {name}님이 직접 두 이야기를 나란히 놓고 함께 들여다볼 거예요.",
      "서로 다른 순간에, 같은 마음으로 빠져든 순간이잖아요.",
      "분명 어떤 공통된 결이 흐르고 있을 거예요.",
      "그 안에 흐르는 공통점이 있다면, 어떤 것이 있을까요?",
      "내가 했던 행동, 느꼈던 감정, 상황적 요인, 함께했던 사람들 등 다양한 요소들을 고려해보세요.",
    ],
    inputHint: "비슷한 감정, 비슷한 행동, 비슷한 상황 — 어떤 형태든 좋아요. 떠오르는 대로 적어주세요.",
    reviewFields: [
      { label: "첫 번째 이야기", field: "flowExperience1" },
      { label: "두 번째 이야기", field: "flowExperience2" },
    ],
    saveTo: "commonPattern",
    buttonLabel: "건네기",
    next: "1-5qf",
  },
  {
    id: "1-5qf",
    chapter: 1,
    kind: "followup",
    owl: "thinking",
    owlPool: INTERVIEW_OWL_POOL,
    timeOfDay: "sunset",
    judge: "judgeBranch",
    parentSaveTo: "commonPattern",
    maxFollowups: 2,
    branches: {
      A: {
        narration: "편집장이 고개를 끄덕인다. 그런데 조금 더 들어가보고 싶다.",
        lines: [
          "그 새로움 안에서 {name}님이 진짜 즐기고 계셨던 건 무엇이었을까요?",
          "그 안의 어떤 부분이 {name}님을 그렇게 빠져들게 했나요?",
        ],
        inputHint: "활동이나 상황 너머 — 그 안의 {name}님을 들여다봐주세요.",
      },
      B: {
        narration: "편집장이 잠깐 시선을 떨어뜨렸다가 다시 든다. 다른 방향으로 들어가보기로 한다.",
        lines: [
          "괜찮아요, 천천히 가도 돼요.",
          "그 두 순간에 {name}님이 가장 잘 다루고 계셨던 게 있다면 — 어떤 거였을까요?",
          "남들은 어려워하는데 {name}님은 자연스럽게 해내고 있던 부분이요.",
        ],
        inputHint: "잘 다뤘던 것, 자연스럽게 해냈던 것 — 떠오르는 대로 적어주세요.",
      },
      D: { next: "1-5c" },
    },
    buttonLabel: "건네기",
  },
  {
    id: "1-5c",
    chapter: 1,
    kind: "owlNarration",
    owl: "thinking",
    owlPool: INTERVIEW_OWL_POOL,
    timeOfDay: "sunset",
    lines: [
      "이야기하다보니 어느새 시간이 많이 흘렀네요.",
    ],
    next: "1-6",
  },
  {
    // 조명 꺼진 객실 — "창밖이 어둑해진다" 멘트
    id: "1-6",
    chapter: 1,
    kind: "ambience",
    owl: "closingBook",
    timeOfDay: "starsRising",
    bgImage: "/vision_express/common/Chapter02-1.jpg",
    narration: "창밖이 어둑해진다.",
    next: "1-6b",
  },
  {
    // 스위치 효과음과 함께 조명이 켜진 객실로 전환
    id: "1-6b",
    chapter: 1,
    kind: "ambience",
    owl: "closingBook",
    timeOfDay: "starsRising",
    bgImage: "/vision_express/common/Chapter02-3.jpg",
    bgm: "dragon-studio-light-switch-on-382714.mp3",
    lines: [
      "객실 램프를 켜둘게요.",
    ],
    next: "2-card",
  },
];
