import { INTERVIEW_OWL_POOL, type SceneSpec } from "./types";
import { RECEIVE_OPENERS } from "./openers";

export const CH4_SCENES: SceneSpec[] = [
  {
    id: "4-card",
    chapter: 4,
    kind: "chapterCard",
    timeOfDay: "dawnPink",
    bgImage: "/vision_express/common/chapter04.webp",
    bgm: "benkirb-shine-10-268906.mp3",
    next: "4-1",
  },
  {
    id: "4-1",
    chapter: 4,
    kind: "owlNarration",
    owl: "contemplating",
    owlPool: INTERVIEW_OWL_POOL,
    timeOfDay: "dawnPink",
    bgImage: "/vision_express/common/chapter04-1.webp",
    narration: "편집장이 회중시계를 꺼내 바라본다. 지평선에 옅은 빛이 번지기 시작한다.",
    pageSize: 1,
    lines: [
      "열차가 한참을 달려왔네요.",
      "창밖을 보시면 — 지평선이 조금씩 밝아오고 있어요.",
      "저희도 이제 거의 다 왔어요.",
    ],
    next: "4-1b",
  },
  {
    id: "4-1b",
    chapter: 4,
    kind: "owlNarration",
    owl: "explaining",
    owlPool: INTERVIEW_OWL_POOL,
    timeOfDay: "dawnPink",
    bgImage: "/vision_express/common/chapter04.webp",
    lines: [
      "거창한 결심은 아니어도 괜찮아요.",
      "{name}님이 그리신 그 비전을 향해 — 내일부터 시작할 수 있는 가장 작은 한 걸음.",
      "그것 하나면 충분해요.",
    ],
    next: "4-2",
  },
  {
    id: "4-2",
    chapter: 4,
    kind: "question",
    timeOfDay: "dawnPink",
    bgImage: "/vision_express/common/chapter04.webp",
    owl: "focusedWriting",
    owlPool: INTERVIEW_OWL_POOL,
    lines: [
      "내일부터 시작해볼 한 가지— 무엇이 있을까요?",
    ],
    editorNote: "올해 안에 해보고 싶은 한 가지를 먼저 떠올려보고, 거기서부터 쪼개어봐도 좋아요.",
    inputHint: "아주 작은 행동이어도 좋아요.",
    placeholder: "예: 좋은 참가자 경험을 일구어낸 사례 (웨비나, 컨퍼런스, 프로그램 등 형식 무관) 찾아보기",
    saveTo: "firstStep",
    buttonLabel: "건네기",
    // [2026-05-20] reviewFields 제거 — 3-10b timeHorizon 단계가 사라지면서
    // visionSummary/timeHorizon1/2/3 필드가 모두 dead가 됐고, 패널이 항상
    // "아직 답변이 없어요"만 4줄 띄워서 사용자 혼동만 유발. 깨끗이 제거.
    next: "4-3",
  },
  {
    id: "4-3",
    chapter: 4,
    kind: "followup",
    timeOfDay: "dawnPink",
    bgImage: "/vision_express/common/chapter04.webp",
    owl: "thinking",
    owlPool: INTERVIEW_OWL_POOL,
    judge: "judgeBranch",
    parentSaveTo: "firstStep",
    maxFollowups: 2,
    branches: {
      A: {
        openerPool: RECEIVE_OPENERS,
        lines: [
          "그 '열심히'가 어떤 모습일까요?",
          "내일 아침에 책상 앞에 앉아서 — {name}님이 가장 먼저 하실 일은 무엇인가요?",
        ],
      },
      B: {
        lines: [
          "큰 그림이 있으시군요.",
          "그런데 그 큰 결심을 향한 가장 작은 첫 걸음은 무엇일까요?",
          "내일 하루 안에 끝낼 수 있는 작은 한 가지로 좁혀볼까요.",
        ],
      },
      D: { next: "4-4" },
    },
    buttonLabel: "건네기",
  },
  {
    id: "4-4",
    chapter: 4,
    kind: "owlNarration",
    timeOfDay: "dawnPink",
    bgImage: "/vision_express/common/chapter04.webp",
    owl: "explaining",
    lines: [
      "그 첫 걸음이 조금 더 또렷해졌어요.",
      "그런데 {name}님 — 한 가지만 더 생각해볼까요.",
      "{name}님이 디딜 그 첫 걸음을 — 혼자 디디지 않으셔도 돼요.",
      "{name}님 곁에는 이미 함께 해줄 수 있는 사람들과 자원들이 있을 거예요.",
    ],
    next: "4-5",
  },
  {
    id: "4-5",
    chapter: 4,
    kind: "question",
    timeOfDay: "dawnPink",
    bgImage: "/vision_express/common/chapter04.webp",
    owl: "thinking",
    owlPool: INTERVIEW_OWL_POOL,
    lines: [
      "그 첫 걸음을 뗄 때 — 누구에게 도움을 받을 수 있을까요?",
      "동료, 선배, 혹은 가까운 사람 누구든 좋아요.",
      "만약 주변에 없다면, 평소 SNS 상에서 좋아하는 인플루언서, 존경하는 작가 등 참고할 수 있는 인물도 괜찮아요.",
    ],
    inputHint: "떠오르는 분의 이름이나 어떤 관계의 사람인지 적어주세요.",
    saveTo: "supportPerson",
    buttonLabel: "건네기",
    // [2026-05-20] reviewFields 제거 — 4-2와 동일 이유 (dead timeHorizon 필드).
    next: "4-6",
  },
  {
    id: "4-6",
    chapter: 4,
    kind: "question",
    timeOfDay: "dawnPink",
    bgImage: "/vision_express/common/chapter04.webp",
    owl: "thinking",
    owlPool: INTERVIEW_OWL_POOL,
    lines: [
      "그리고 그 첫 걸음을 단단하게 만들어줄 수 있는 자원이 확보되어야 할 것 같아요.",
      "무엇이 있을까요?",
      "시간이나 공간, 필요한 툴이나 스킬, 공부해야 할 자료 등 자유롭게 생각해보세요.",
    ],
    inputHint: "지금 가장 필요하다고 느끼는 자원을 떠올려보셔도 좋아요.",
    saveTo: "neededResource",
    buttonLabel: "건네기",
    next: "4-6b",
  },
  {
    id: "4-6b",
    chapter: 4,
    kind: "followup",
    timeOfDay: "dawnPink",
    bgImage: "/vision_express/common/chapter04.webp",
    owl: "thinking",
    owlPool: INTERVIEW_OWL_POOL,
    judge: "judgeBranch",
    parentSaveTo: "neededResource",
    maxFollowups: 2,
    branches: {
      A: {
        lines: [
          "그 첫 걸음을 디딜 때 — 지금 {name}님에게 가장 부족하다고 느끼시는 게 있다면 무엇이세요?",
          "그게 단서가 될 거예요.",
        ],
      },
      D: { next: "4-8" },
    },
    buttonLabel: "건네기",
  },
  {
    id: "4-8",
    chapter: 4,
    kind: "ritual",
    timeOfDay: "dawnPink",
    bgImage: "/vision_express/common/chapter05.webp",
    owl: "approving",
    lines: [
      "긴 시간 고생 많으셨어요.",
    ],
    buttonLabel: "네",
    next: "C-1",
  },
];
