"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { pdf } from "@react-pdf/renderer";
import { AutoFlowText } from "@/components/v3/ui/AutoFlowText";
import { StoryButtonV3 } from "@/components/v3/ui/StoryButtonV3";
import { useV3Session } from "@/components/v3/context/V3SessionContext";
import { extractIdentityTitle, renderTemplate } from "@/lib/v3/scenes/template";
import { llm } from "@/lib/v3/llm";
import { MagazinePDF, type MagazineData } from "@/lib/v3/pdf/MagazinePDF";
import { registerPdfFonts } from "@/lib/v3/pdf/fonts";
import type { SceneSpec, SceneId } from "@/lib/v3/scenes/types";

type Status = "loading" | "ready" | "error";

export function MagazineHandoffScene({ spec, onAdvance }: { spec: SceneSpec; onAdvance: (n: SceneId) => void }) {
  const { session, patch } = useV3Session();
  const [data, setData] = useState<MagazineData | null>(null);
  const [status, setStatus] = useState<Status>("loading");
  const [downloading, setDownloading] = useState(false);

  useEffect(() => {
    registerPdfFonts();
  }, []);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        // Reuse chapter articles already generated by RecordPageScene so the PDF
        // matches the text the participant saw in the chapter pages. Fetch fresh
        // only for chapters whose record page wasn't visited.
        const cached = session.chapterArticles ?? {};
        const articleFor = (n: 1 | 2 | 3 | 4) =>
          cached[n] ??
          llm.writeChapterArticle({
            name: session.name,
            gender: session.gender,
            job: session.job,
            chapter: n,
            session,
          });

        const [coverHeadline, editorIntro, editorOutro, ch1, ch2, ch3, ch4] = await Promise.all([
          llm.writeCoverHeadline({ session }),
          llm.writeEditorNote({ session, kind: "intro" }),
          llm.writeEditorNote({ session, kind: "outro" }),
          articleFor(1),
          articleFor(2),
          articleFor(3),
          articleFor(4),
        ]);
        if (cancelled) return;
        const today = new Date().toISOString().slice(0, 10);
        setData({
          name: session.name,
          date: today,
          coverHeadline,
          editorIntro,
          editorOutro,
          chapters: { 1: ch1, 2: ch2, 3: ch3, 4: ch4 },
        });
        // Cache fetched articles to session so the next scene (C-2b 합본 매거진
        // 스프레드)이 재호출하지 않도록. 캐시에 이미 있던 챕터는 그대로 유지.
        const newlyFetched: Record<number, { headline: string; body: string; pullQuote: string | null }> = {};
        const chaptersToCache: [1 | 2 | 3 | 4, typeof ch1][] = [[1, ch1], [2, ch2], [3, ch3], [4, ch4]];
        for (const [c, art] of chaptersToCache) {
          if (!cached[c] && art) newlyFetched[c] = art;
        }
        if (Object.keys(newlyFetched).length > 0) {
          patch({ chapterArticles: { ...cached, ...newlyFetched } });
        }
        setStatus("ready");
      } catch (err) {
        console.error("[v3] MagazineHandoff load failed:", err);
        if (!cancelled) setStatus("error");
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [session]);

  const handleDownload = async () => {
    if (!data) return;
    setDownloading(true);
    try {
      const blob = await pdf(<MagazinePDF data={data} />).toBlob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `STORY_Vol.${session.name}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("[v3] PDF generation failed:", err);
      alert("PDF 생성 중 오류가 발생했어요. 잠시 후 다시 시도해주세요.");
    } finally {
      setDownloading(false);
    }
  };

  const lines = (spec.lines ?? []).map((l) => renderTemplate(l, session));
  const [settled, setSettled] = useState(false);
  const identityTitle = extractIdentityTitle(session.identityName);

  // Summary fields shown above the download button (QA: 마무리에서 결과를 한번에 읽어보는게 좋지 않을까요).
  // selectedValues에 골라둔 가치가 1~3개 있을 수 있어 모두 표시한다.
  const pickedValues = (session.selectedValues ?? []).filter((v) => v && v.trim().length > 0);
  const valueRows: Array<[string, string]> = pickedValues.map((v) => [
    `'${v}'은 나에게`,
    session.valueDefinitions[v] ?? "",
  ]);
  const summary: Array<[string, string]> = [
    ["이름", session.name],
    ["직무", session.job],
    ["나의 정체성", identityTitle],
    [
      "가장 소중한 가치",
      pickedValues.length > 0 ? pickedValues.join(", ") : session.topValue,
    ],
    ...valueRows,
    ["4년 후 비전", session.visionLine],
    ["내일부터의 한 걸음", session.firstStep],
    ["곁의 사람", session.supportPerson],
    ["필요한 자원", session.neededResource],
  ].filter(([, v]) => v && v.trim().length > 0) as Array<[string, string]>;

  return (
    // No `flex-1` chain — the dialog (FULL_HEIGHT_KINDS) already provides
    // height + overflow-y-auto. Wrapping with flex-1 made child content
    // ignore the cap and spill below the viewport (which has overflow-hidden
    // on <main>), making the summary list + PDF button invisible.
    <div className="flex flex-col gap-5">
      <AutoFlowText lines={lines} onSettled={() => setSettled(true)} />

      {settled && summary.length > 0 && (
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.3 }}
          className="rounded-md border border-[#b99b6b]/30 bg-white/40 p-5"
        >
          <p className="mb-3 text-center text-[16px] uppercase tracking-[0.3em] text-[#8b7050]">
            한 호의 요약
          </p>
          <dl className="space-y-2.5 text-[16px] leading-[1.6]">
            {summary.map(([k, v]) => (
              <div key={k} className="grid grid-cols-[110px_1fr] gap-3">
                <dt className="text-[16px] tracking-wide text-[#8b7050]">{k}</dt>
                <dd className="text-[#3d2414]">{v}</dd>
              </div>
            ))}
          </dl>
        </motion.div>
      )}

      {settled && (
        <p className="text-center text-sm italic text-[#8b7050]">
          {status === "loading" && "편집장이 매거진을 마지막으로 다듬고 있어요…"}
          {status === "ready" && "매거진이 준비됐어요."}
          {status === "error" && "매거진 정리에 잠깐 어려움이 있었어요. 그래도 다운로드는 가능해요."}
        </p>
      )}

      {/* PDF button is sticky to the dialog's bottom edge. The summary list
          (name/job/identity/value/vision/firstStep/...) easily exceeds the
          dialog's max-height on short screens; without `sticky` the button
          scrolled out of reach with the list — same "버튼이 밑으로 내려가서
          클릭이 안 된다" failure as the cardChoice scene. The negative
          -mx-7/-mb-7 + matching px-7 + opaque bg extend this footer to the
          dialog edges (dialog padding is p-7 for FULL_HEIGHT_KINDS). */}
      <div
        className={`sticky bottom-0 z-10 -mx-7 -mb-7 mt-1 flex justify-end px-7 py-3 transition-opacity duration-500 ${
          settled ? "opacity-100" : "pointer-events-none opacity-0"
        }`}
      >
        <StoryButtonV3
          label={
            downloading
              ? "전달 중…"
              : status === "loading"
                ? "잠시만요…"
                : (spec.buttonLabel ?? "PDF 받기")
          }
          onClick={() => {
            if (status !== "ready" || downloading) return;
            void handleDownload();
            // Advance after a beat — gives the browser time to start the download.
            setTimeout(() => {
              if (typeof spec.next === "string") onAdvance(spec.next);
            }, 1200);
          }}
          disabled={status !== "ready" || downloading}
          ritual
        />
      </div>
    </div>
  );
}
