"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { pdf } from "@react-pdf/renderer";
import { AutoFlowText } from "@/components/v3/ui/AutoFlowText";
import { StoryButtonV3 } from "@/components/v3/ui/StoryButtonV3";
import { useV3Session } from "@/components/v3/context/V3SessionContext";
import { buildV3ChapterThreads } from "@/lib/v3/session/adminView";
import { extractIdentityTitle, renderTemplate } from "@/lib/v3/scenes/template";
import { llm } from "@/lib/v3/llm";
import { readUrlConfig } from "@/lib/v3/llm/realLLM";
import { MagazinePDF, type MagazineData } from "@/lib/v3/pdf/MagazinePDF";
import { registerPdfFonts } from "@/lib/v3/pdf/fonts";
import type { SceneSpec, SceneId } from "@/lib/v3/scenes/types";

type Status = "loading" | "ready" | "error";

export function MagazineHandoffScene({ spec, onAdvance }: { spec: SceneSpec; onAdvance: (n: SceneId) => void }) {
  const { session, patch } = useV3Session();
  const [data, setData] = useState<MagazineData | null>(null);
  const [status, setStatus] = useState<Status>("loading");
  const [downloading, setDownloading] = useState(false);

  useEffect(() => {
    registerPdfFonts();
  }, []);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        // Reuse chapter articles already generated by RecordPageScene so the PDF
        // matches the text the participant saw in the chapter pages. Fetch fresh
        // only for chapters whose record page wasn't visited.
        const cached = session.chapterArticles ?? {};
        const articleFor = (n: 1 | 2 | 3 | 4) =>
          cached[n] ??
          llm.writeChapterArticle({
            name: session.name,
            gender: session.gender,
            job: session.job,
            chapter: n,
            session,
          });

        const [coverHeadline, editorIntro, editorOutro, ch1, ch2, ch3, ch4] = await Promise.all([
          llm.writeCoverHeadline({ session }),
          llm.writeEditorNote({ session, kind: "intro" }),
          llm.writeEditorNote({ session, kind: "outro" }),
          articleFor(1),
          articleFor(2),
          articleFor(3),
          articleFor(4),
        ]);
        if (cancelled) return;
        const today = new Date().toISOString().slice(0, 10);
        setData({
          name: session.name,
          date: today,
          coverHeadline,
          editorIntro,
          editorOutro,
          chapters: { 1: ch1, 2: ch2, 3: ch3, 4: ch4 },
        });
        // Cache fetched articles to session so the next scene (C-2b 합본 매거진
        // 스프레드)이 재호출하지 않도록. 캐시에 이미 있던 챕터는 그대로 유지.
        const newlyFetched: Record<number, { headline: string; body: string; pullQuote: string | null }> = {};
        const chaptersToCache: [1 | 2 | 3 | 4, typeof ch1][] = [[1, ch1], [2, ch2], [3, ch3], [4, ch4]];
        for (const [c, art] of chaptersToCache) {
          if (!cached[c] && art) newlyFetched[c] = art;
        }
        if (Object.keys(newlyFetched).length > 0) {
          patch({ chapterArticles: { ...cached, ...newlyFetched } });
        }
        setStatus("ready");
      } catch (err) {
        console.error("[v3] MagazineHandoff load failed:", err);
        if (!cancelled) setStatus("error");
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [session]);

  const handleDownload = async () => {
    if (!data) return;
    setDownloading(true);
    try {
      const blob = await pdf(<MagazinePDF data={data} deep={readUrlConfig().deep} />).toBlob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `STORY_Vol.${session.name}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("[v3] PDF generation failed:", err);
      alert("PDF 생성 중 오류가 발생했어요. 잠시 후 다시 시도해주세요.");
    } finally {
      setDownloading(false);
    }
  };

  const lines = (spec.lines ?? []).map((l) => renderTemplate(l, session));
  const [settled, setSettled] = useState(false);
  const identityTitle = extractIdentityTitle(session.identityName);

  // Summary fields shown above the download button (QA: 마무리에서 결과를 한번에 읽어보는게 좋지 않을까요).
  // selectedValues에 골라둔 가치가 1~3개 있을 수 있어 모두 표시한다.
  const pickedValues = (session.selectedValues ?? []).filter((v) => v && v.trim().length > 0);
  const valueRows: Array<[string, string]> = pickedValues.map((v) => [
    `'${v}'은 나에게`,
    session.valueDefinitions[v] ?? "",
  ]);
  const summary: Array<[string, string]> = [
    ["이름", session.name],
    ["직무", session.job],
    ["나의 정체성", identityTitle],
    [
      "가장 소중한 가치",
      pickedValues.length > 0 ? pickedValues.join(", ") : session.topValue,
    ],
    ...valueRows,
    ["5년 후 비전", session.visionLine],
    ["내일부터의 한 걸음", session.firstStep],
    ["곁의 사람", session.supportPerson],
    ["필요한 자원", session.neededResource],
  ].filter(([, v]) => v && v.trim().length > 0) as Array<[string, string]>;

  return (
    // [2026-05-20] register/freetext와 동일 패턴: 내부 스크롤 영역(flex-1
    // min-h-0 overflow-y-auto) + 고정 푸터(shrink-0). 풀 세션에서 요약이
    // 8~12줄로 길어져도 스크롤 영역 안에서 스크롤되고, 버튼은 항상 카드 하단에
    // 고정 보임. dialog wrapper는 overflow-hidden이라 이중 스크롤 없음.
    <div className="flex min-h-0 flex-1 flex-col">
      <div className="min-h-0 flex-1 space-y-5 overflow-y-auto pr-1">
        <AutoFlowText lines={lines} onSettled={() => setSettled(true)} />

        {settled && summary.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="rounded-md border border-[#b99b6b]/30 bg-white/40 p-5"
          >
            <p className="mb-3 text-center text-[16px] uppercase tracking-[0.14em] text-[#8b7050]">
              한 호의 요약
            </p>
            <dl className="space-y-2.5 text-[16px] leading-[1.6]">
              {summary.map(([k, v]) => (
                <div key={k} className="grid grid-cols-[145px_1fr] gap-3">
                  <dt className="break-keep whitespace-nowrap text-[16px] tracking-wide text-[#8b7050]">{k}</dt>
                  <dd className="break-keep text-[#3d2414]">{v}</dd>
                </div>
              ))}
            </dl>
          </motion.div>
        )}

        {settled && (
          <p className="text-center text-sm italic text-[#8b7050]">
            {status === "loading" && "편집장이 매거진을 마지막으로 다듬고 있어요…"}
            {status === "ready" && "매거진이 준비됐어요."}
            {status === "error" && "매거진 정리에 잠깐 어려움이 있었어요. 그래도 다운로드는 가능해요."}
          </p>
        )}

        {settled && <ChapterAttachment session={session} />}
      </div>

      {/* 고정 푸터 — scroll 영역 밖 shrink-0. 항상 카드 하단에 보임. */}
      <div
        className={`shrink-0 mt-4 flex justify-end border-t border-[#d7bd83]/20 pt-4 transition-opacity duration-500 ${
          settled ? "opacity-100" : "pointer-events-none opacity-0"
        }`}
      >
        <StoryButtonV3
          label={
            downloading
              ? "전달 중…"
              : status === "loading"
                ? "잠시만요…"
                : (spec.buttonLabel ?? "PDF 받기")
          }
          onClick={() => {
            if (status !== "ready" || downloading) return;
            void handleDownload();
            // Advance after a beat — gives the browser time to start the download.
            setTimeout(() => {
              if (typeof spec.next === "string") onAdvance(spec.next);
            }, 1200);
          }}
          disabled={status !== "ready" || downloading}
          ritual
        />
      </div>
    </div>
  );
}

/** 별첨 — 챕터 1/2/3/4 의 매거진 요약 + 사용자가 적었던 답변 전체를 결과지 안에서
 *  한 번에 모아 보기 위한 접이식 섹션. 기본 닫힘 — 펼치면 ChapterReviewOverlay
 *  와 동일한 구조(질문/답변/AI 결과 분리)로 렌더한다. 데이터 소스는 어드민/기록
 *  패널과 동일하게 buildV3ChapterThreads 를 재사용해 진실의 원천을 일치시킨다. */
function ChapterAttachment({ session }: { session: import("@/lib/v3/scenes/types").V3Session }) {
  const [open, setOpen] = useState(false);
  const threads = buildV3ChapterThreads(session).filter((t) =>
    t.entries.some((e) => e.text && e.text.trim().length > 0),
  );
  if (threads.length === 0) return null;

  return (
    <motion.section
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6, delay: 0.5 }}
      className="rounded-md border border-[#b99b6b]/30 bg-white/35 p-5"
    >
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="flex w-full items-center justify-between text-left"
        aria-expanded={open}
      >
        <div>
          <p className="text-[12px] uppercase tracking-[0.14em] text-[#8b7050]">Appendix</p>
          <p className="mt-1 text-[16px] font-semibold text-[#3d2414]">
            별첨 — 내가 적은 기록과 챕터별 요약 전체 보기
          </p>
          <p className="mt-1 text-[13px] italic text-[#8b7050]">
            네 챕터에서 주고받은 질문·답변·편집장 요약을 한 자리에 모아둔 페이지예요.
          </p>
        </div>
        <span className="ml-3 shrink-0 text-[20px] text-[#8b7050]" aria-hidden>
          {open ? "−" : "+"}
        </span>
      </button>

      {open && (
        <div className="mt-5 space-y-6">
          {threads.map((thread) => {
            const entries = thread.entries.filter((e, i, arr) => {
              if (!e.text || e.text.trim().length === 0) return false;
              if (e.tone === "question") {
                const next = arr[i + 1];
                const answered = next?.text && next.text.trim().length > 0;
                if (!answered) return false;
              }
              return true;
            });
            if (entries.length === 0) return null;
            return (
              <div key={thread.chapter} className="space-y-3">
                <div className="border-b border-[#b99b6b]/30 pb-2">
                  <p className="text-[11px] uppercase tracking-[0.1em] text-[#9b8768]">
                    {thread.chapter}
                  </p>
                  <h4 className="mt-0.5 text-[16px] font-semibold text-[#3d2414]">
                    {thread.title}
                  </h4>
                </div>
                <div className="space-y-2.5">
                  {entries.map((entry, i) => {
                    const isQuestion = entry.tone === "question";
                    const isResult = entry.tone === "result";
                    const boxClass = isQuestion
                      ? "rounded-md border-l-[3px] border-[#b99b6b] bg-transparent px-3 py-1.5"
                      : isResult
                        ? "rounded-md border border-[#d7bd83]/40 bg-[#ede1c6]/40 px-3 py-2.5"
                        : "rounded-md border border-[#b99b6b]/30 bg-white/55 px-3 py-2.5";
                    const labelClass = isQuestion
                      ? "text-[11px] uppercase tracking-[0.08em] text-[#9b8768]"
                      : "text-[12px] tracking-wide text-[#8b7050]";
                    const textClass = isQuestion
                      ? "mt-1 whitespace-pre-wrap text-[14px] italic leading-[1.55] text-[#6b5337]"
                      : "mt-1.5 whitespace-pre-wrap text-[14px] leading-[1.65] text-[#3d2414]";
                    return (
                      <div key={i} className={boxClass}>
                        <p className={labelClass}>{entry.label}</p>
                        <div className={textClass}>{entry.text}</div>
                      </div>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </motion.section>
  );
}
